### ISSUE TITLE
"debugger" statement in build/index.js when installing from npm

### ISSUE THREAD

**Issue by ebbe-brandstrup** [feats/babel-plugin-inline-import#5]
Hi and thanks for this useful Babel plugin! 

I am having trouble debugging my Node graphql server app because the ```build/index.js``` file in the npm installation has a ```debugger;``` statement in line 21 which is causing my debugger to stop there for every import statement I have that the plugin is configured to handle.

Can you please re-publish to npm? The ```debugger;``` statement isn't in your source code on GitHub so it seems to me it was a mistake that the last published version had it in there and you've since removed it from the source but didn't publish since?

**Comment by zvictor** [comment]
shame on me!
it should be fixed now, thanks.
