### ISSUE TITLE
caching issue

### ISSUE THREAD

**Issue by scf4** [feats/babel-plugin-inline-import#7]
There seems to be some sort of caching going on. It doesn't seem to realize the .graphql file has changed unless I rename the filename.

I've had this happen on 3 separate projects.

**Comment by zvictor** [comment]
Is it something different than what we described in the [Caveats](https://github.com/Quadric/babel-plugin-inline-import#caveats) section?

> Babel does not track dependency between imported and importing files after the transformation is made. Therefore, you need to change the importing file in order to see your changes in the imported file spread.

**Comment by jlengstorf** [comment]
~~It's not different from what was described, but it's a pretty big source of confusion when working on a team. Is this something that could be configurable? I don't know enough about Babel internals to know if this is easy/feasible, but it would be a huge help for working with `.graphql` files, for example.~~

I just read the next line in the Caveats section:

> To overcome this, you can:
> 
> - Disable babel cache (`BABEL_DISABLE_CACHE=1`)

That was all I needed. Thanks!
